### ISSUE TITLE
Missing ReadBytes() Method

### ISSUE THREAD

**Issue by dhkatz** [EvidentlyCube/csharp-binary-stream#1]
Hey, just want to say you've done some great work on this package. Has made porting some C# code a ton easier.

BinaryReader does not currently support the [ReadBytes()](https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader.readbytes?view=netframework-4.7.2) method. This isn't really a huge deal but it means instead of simply calling readBytes(count) I would have to iterate and call readByte() multiple times (which I've done easiest through `[...Array(count)].map(() => reader.readByte());`).

**Comment by EvidentlyCube** [comment]
@dhkatz I think I can do something about that :)

**Comment by EvidentlyCube** [comment]
I just published `1.0.1` which includes `readBytes` on `BinaryReader`!
